<?php

return [
    'enabled' => env('AI_ENABLED', 'off'),
    'provider' => env('AI_PROVIDER', 'openai'),
    'base_url' => env('AI_BASE_URL'),
    'api_key' => env('AI_API_KEY'),
    'model' => env('AI_MODEL'),
    'routes' => [
        ['label' => 'Dashboard', 'path' => '/v10/dashboard', 'keywords' => ['dashboard', 'admin dashboard']],
        ['label' => 'Staff Dashboard', 'path' => '/v25/staff-dashboard', 'keywords' => ['staff dashboard', 'teacher dashboard']],
        ['label' => 'My Profile', 'path' => '/v25/profile', 'keywords' => ['my profile', 'profile']],
        ['label' => 'Session', 'path' => '/v11/all-sessions', 'keywords' => ['sessions', 'session list', 'academic sessions', 'view sessions']],
        ['label' => 'Term', 'path' => '/v11/all-terms', 'keywords' => ['terms', 'term list', 'academic terms', 'view terms']],
        ['label' => 'Subject', 'path' => '/v16/all-subjects', 'keywords' => ['subjects', 'subject list', 'view subjects']],
        ['label' => 'Class', 'path' => '/v12/all-classes', 'keywords' => ['classes', 'class list', 'view classes']],
        ['label' => 'Class Arm', 'path' => '/v12/all-class-arms', 'keywords' => ['class arms', 'class arm list', 'view class arms']],
        ['label' => 'Result Pin', 'path' => '/v19/pins', 'keywords' => ['result pins', 'pin list', 'view pins']],
        ['label' => 'View Parent', 'path' => '/v13/all-parents', 'keywords' => ['parents', 'parent list', 'view parents']],
        ['label' => 'Add Parent', 'path' => '/v13/add-parent', 'keywords' => ['add parent', 'create parent', 'new parent']],
        ['label' => 'View Staff', 'path' => '/v15/all-staff', 'keywords' => ['staff list', 'view staff', 'all staff']],
        ['label' => 'Add Staff', 'path' => '/v15/add-staff', 'keywords' => ['add staff', 'create staff', 'new staff', 'add staff member', 'create staff member']],
        ['label' => 'View Student', 'path' => '/v14/all-students', 'keywords' => ['students', 'student list', 'view students', 'all students']],
        ['label' => 'Add Student', 'path' => '/v14/add-student', 'keywords' => ['add student', 'create student', 'new student', 'register student', 'student admission']],
        ['label' => 'Bulk Result Print', 'path' => '/v14/bulk-results', 'keywords' => ['bulk results', 'bulk result print', 'print results']],
        ['label' => 'Check Student Result', 'path' => '/v14/check-result', 'keywords' => ['check result', 'view result', 'student result']],
        ['label' => 'Early Years Report', 'path' => '/v14/early-years-report', 'keywords' => ['early years report', 'ey report']],
        ['label' => 'Result Entry', 'path' => '/v19/results-entry', 'keywords' => ['enter results', 'result entry', 'enter result', 'enter student result', 'input results']],
        ['label' => 'Class Skill Ratings', 'path' => '/v14/class-skill-ratings', 'keywords' => ['skill ratings', 'class skill ratings']],
        ['label' => 'Student Bulk Upload', 'path' => '/v22/bulk-student-upload', 'keywords' => ['bulk upload students', 'student bulk upload', 'upload students']],
        ['label' => 'Student Promotion', 'path' => '/v20/student-promotion', 'keywords' => ['student promotion', 'promote students']],
        ['label' => 'Promotion Reports', 'path' => '/v20/promotion-reports', 'keywords' => ['promotion reports', 'promotion history']],
        ['label' => 'Subject to Class', 'path' => '/v17/assign-subjects', 'keywords' => ['assign subjects', 'subject to class', 'subject assignment']],
        ['label' => 'Teachers to Subject', 'path' => '/v17/assign-teachers', 'keywords' => ['assign teachers', 'teachers to subject', 'teacher assignment']],
        ['label' => 'Teachers to Class', 'path' => '/v18/assign-class-teachers', 'keywords' => ['assign class teachers', 'class teacher', 'teacher to class']],
        ['label' => 'Student Attendance', 'path' => '/v21/student-attendance', 'keywords' => ['student attendance', 'mark student attendance']],
        ['label' => 'Staff Attendance', 'path' => '/v21/staff-attendance', 'keywords' => ['staff attendance', 'mark staff attendance']],
        ['label' => 'Attendance Reports', 'path' => '/v21/attendance-dashboard', 'keywords' => ['attendance report', 'attendance dashboard']],
        ['label' => 'Quiz Panel', 'path' => '/v27/cbt/admin', 'keywords' => ['cbt admin', 'quiz panel', 'cbt']],
        ['label' => 'CBT Link', 'path' => '/v27/cbt/admin/cbt-link', 'keywords' => ['cbt link', 'quiz link']],
        ['label' => 'Grading Scale & Result Page', 'path' => '/v19/grade-scales', 'keywords' => ['grading scale', 'grade scale', 'result page']],
        ['label' => 'Skills', 'path' => '/v19/skills', 'keywords' => ['skills', 'skill categories']],
        [
            'label' => 'Assessment Components',
            'path' => '/v19/assessment-components',
            'keywords' => ['assessment components', 'assessment component'],
            'description' => 'Assessment components define the score breakdown (e.g., CA1, CA2, exams) that make up a student result.',
        ],
        ['label' => 'Assessment Structure', 'path' => '/v19/assessment-structures', 'keywords' => ['assessment structures', 'assessment structure']],
        ['label' => 'Academic-Rollover', 'path' => '/v20/academic-rollover', 'keywords' => ['academic rollover', 'rollover']],
        ['label' => 'Roles', 'path' => '/v24/roles', 'keywords' => ['roles', 'view roles']],
        ['label' => 'User Roles', 'path' => '/v24/user-roles', 'keywords' => ['user roles', 'assign roles']],
        ['label' => 'School Settings', 'path' => '/v10/profile', 'keywords' => ['school settings', 'school profile']],
    ],
];
